/** biome-ignore-all lint/a11y/useValidAnchor: external content */
/** biome-ignore-all lint/performance/noImgElement: external content */
import { XIcon } from "lucide-react";
import { useEffect, useState } from "react";
import { createPortal } from "react-dom";

export default function PrivacyModal({
	active,
	closeButton,
}: {
	active: boolean;
	closeButton: () => void;
}) {
	const [mounted, setMounted] = useState(false);

	useEffect(() => {
		setMounted(true);
		return () => setMounted(false);
	}, []);

	if (!mounted) return null;

	const modalContent = (
		<div
			className={`att ${active ? "top-0" : "top-full"} fixed right-0 bottom-0 left-0 z-[9999] flex flex-col overflow-y-auto bg-white text-neutral-900 transition-all duration-500`}
		>
			<div className="flex justify-end">
				<button
					type="button"
					className="mt-3 mr-5 rounded-full bg-att-blue p-1"
					onMouseDown={() => {
						closeButton();
					}}
				>
					<XIcon className="h-6 w-6 rounded-full text-white" strokeWidth={3} />
				</button>
			</div>
			<div className="privacy-content relative flex flex-grow flex-col px-5 pt-1 pb-5">
				<h1>AT&amp;T Privacy Notice</h1>
				<p>
					<b>Effective July 2, 2025</b>
				</p>

				<p>
					Thank you for reading our Privacy Notice. Your privacy is important to
					you and to us. This notice explains how we use your information and
					keep it safe. &nbsp;
				</p>
				<p>
					Importantly, this notice explains the choices you can make at any time
					about how your information may be used.
				</p>
				<p>
					This notice applies to your interactions with AT&amp;T and its
					products and services including internet, wireless, voice, and
					AT&amp;T apps. We will tell you if a different notice applies. For
					example:
				</p>
				<ul>
					<li>Cricket has its own privacy notice.</li>
					<li>
						AT&amp;T business customers may have a service agreement that covers
						the handling of their information. The service agreement controls if
						it is different from this Privacy Notice.
					</li>
					<li>
						For AT&amp;T business customers outside the United States,
						<a
							href="https://about.att.com/privacy/global_approach/biz-notice-mow.html"
							target="_blank"
							rel="noopener"
						>
							the AT&amp;T Business Customer Privacy Notice – Most of World
						</a>
						&nbsp;governs if it is different from this Privacy Notice.
					</li>
				</ul>
				<p>
					Please make sure everyone who uses your account knows they are covered
					by this notice.
				</p>

				<h3>The information we collect</h3>

				<p>
					To better run our business, we collect information about you, your
					equipment, and how you use our products and services. This includes:
				</p>
				<ul>
					<li>
						<b>Account information.</b>&nbsp;Information you give us about
						yourself, such as contact and billing information, service-related
						history and details, including&nbsp;
						<a
							href="https://www.att.com/consent/cpni/"
							target="_blank"
							rel="noopener"
						>
							Customer Proprietary Network Information
						</a>
						.
					</li>
					<li>
						<b>Equipment information.</b>&nbsp;Information about equipment on
						our network like the type of device you use, device ID, and phone
						number.
						<br />
					</li>
					<li>
						<b>Network performance.</b>&nbsp;We monitor and test the health and
						performance of our network. This includes your use of Products and
						Services to show how our network and your device are working.
						<br />
					</li>
					<li>
						<b>Location information.</b>&nbsp;Location data is automatically
						generated when devices, products and services interact with cell
						towers and Wi-Fi routers. Location data can also be generated by
						Bluetooth services, network devices and other technology, including
						GPS satellites. ​<br />
					</li>
					<li>
						<b>Web browsing and app information</b>.&nbsp;We automatically
						collect a variety of information, which may include time spent on
						websites or apps, website and IP addresses and advertising IDs,
						links and ads seen, videos watched, search terms entered, and items
						placed in online AT&amp;T shopping carts. We may use pixels,
						cookies, and similar tools to collect this information. We don’t
						decrypt information from secure websites or apps – such as passwords
						or banking information.
						<br />
					</li>
					<li>
						<b>Biometric information.</b>&nbsp;Fingerprints, voice prints, and
						face scans are examples of biological characteristics that may be
						used to identify individuals. Learn more in our&nbsp;
						<a
							href="https://about.att.com/privacy/privacy-notice/biometrics.html"
							target="_blank"
							rel="noopener"
						>
							Biometric Information Privacy Notice
						</a>
						.
					</li>
					<li>
						<b>Third-party information.</b>&nbsp;We get information from outside
						sources like credit reports, marketing mailing lists, and
						commercially available demographic and geographic data. Social media
						posts also may be collected, if you reach out to us directly on
						social media or mention AT&amp;T. Sometimes this data is
						de-identified, aggregated, or anonymized.
						<br />
					</li>
				</ul>
				<p>
					All these types of information are considered personal information
					when they can reasonably be linked to you as an identifiable person or
					your household. For instance, information is personal when it can be
					linked to your name, account number, or device.
				</p>

				<h3>How we use your information</h3>

				<p>
					We rely on the information we collect to support our business
					functions, power our services, and improve your experience, such as
					when we:
				</p>
				<ul>
					<li>Provide our products and services.</li>
					<li>Contact you.</li>
					<li>
						Improve your experience and safety. This includes verifying your
						identity, detecting and preventing fraud, protecting your financial
						accounts, authorizing transactions and assisting your interactions
						with us.
					</li>
					<li>Improve and protect our network.</li>
					<li>
						Use it to help understand which additional products and services may
						interest you and others, including combining it with the information
						from testing and running our network. (We don’t access or use the
						content of your texts, emails or calls for this or any other
						marketing and advertising, but we may use your communications
						directly to us for these purposes.)
					</li>
					<li>
						Design and deliver advertising, marketing and promotional campaigns
						to you and others – and measuring their effectiveness (
						<a
							href="https://www.att.com/acctmgmt/passthrough/PRIVACYCHOICES?origination_point=PrivacyCenter"
							target="_blank"
							rel="noopener"
						>
							See your choices
						</a>
						).
					</li>
					<li>
						Use it for billing, collection, and protection of our property and
						legal rights.
					</li>
					<li>
						Prevent and investigate security issues, illegal activities and
						violations of our terms and conditions.
					</li>
					<li>
						De-identify, aggregate, or anonymize it to protect your privacy and
						security. We don’t try to re-identify this data or associate it with
						an individual person except to evaluate the effectiveness of our
						de-identification policies and procedures.
					</li>
					<li>
						Conduct research and create aggregated reports – reports that offer
						insights about groups of customers, but not individuals (we do not
						attempt to re-identify individuals in aggregated reports).
					</li>
				</ul>

				<h3>How we share your information</h3>

				<p>
					As described in the following paragraphs, AT&amp;T shares information
					among the AT&amp;T family of companies. We also share with
					non-AT&amp;T companies.
				</p>
				<p>
					<b>AT&amp;T affiliates.</b>&nbsp;We share information that identifies
					you personally with our affiliates, such as Gigapower and Cricket.
					When we share this information, they must follow this Privacy Notice
					regarding your information, not just their own notice. This includes
					the&nbsp;
					<a
						href="https://www.att.com/acctmgmt/passthrough/PRIVACYCHOICES?origination_point=PrivacyCenter"
						target="_blank"
						rel="noopener"
					>
						privacy choices
					</a>
					you make with AT&amp;T.
				</p>
				<p>
					<b>
						AT&amp;T affiliates and non-AT&amp;T companies for advertising and
						marketing.
					</b>
					&nbsp;We may share information with affiliates and other companies to
					deliver our ads and marketing or to assess their effectiveness. In
					some instances, we may share your information with non-AT&amp;T
					companies that combine your information with theirs to better identify
					audiences and deliver ads on behalf of advertisers, including
					AT&amp;T, (Learn more about our ad programs and see&nbsp;
					<a
						href="https://www.att.com/acctmgmt/passthrough/PRIVACYCHOICES?origination_point=PrivacyCenter"
						target="_blank"
						rel="noopener"
					>
						your choices
					</a>
					.)
				</p>
				<p>
					<b>Non-AT&amp;T companies providing a service.</b>&nbsp;We use
					suppliers for services like marketing, billing, and to support our
					products. When we share your information with suppliers, we require
					them to use it only for the intended purpose and to protect it
					consistent with this notice.
				</p>
				<p>
					<b>Non-AT&amp;T companies for identity verification.</b>&nbsp;We share
					your information with companies such as your bank to protect you from
					fraud, authenticate your identity, protect your financial accounts and
					authorize transactions. When we share for this purpose, we require
					them to use it only for the intended purpose and to protect it,
					consistent with this notice. (Learn more and&nbsp;
					<a
						href="https://www.att.com/acctmgmt/passthrough/PRIVACYCHOICES?origination_point=PrivacyCenter"
						target="_blank"
						rel="noopener"
					>
						see your choices
					</a>
					, including your right to decline this service.)
				</p>
				<p>
					<b>
						Non-AT&amp;T companies and non-branded affiliates with your consent.
					</b>
					&nbsp;If we have your opt-in consent, we may share your information,
					consistent with your direction.
				</p>

				<p>
					<b>
						Non-AT&amp;T companies or entities where authorized or required by
						law.
					</b>
					This can happen when we:
				</p>
				<ul>
					<li>
						Comply with court orders, subpoenas, and lawful discovery requests,
						and as otherwise authorized or required by law. Like all companies,
						we must comply with legal requirements. You can learn more in our
						<a
							href="https://about.att.com/privacy/transparencyreport.html"
							target="_blank"
							rel="noopener"
						>
							Transparency Report
						</a>
						.
					</li>
					<li>Detect and prevent fraud.</li>
					<li>
						Provide or obtain information related to payment for your service.
					</li>
					<li>
						Route your calls or other communications, like connecting calls or
						text messages with other carrier networks.
					</li>
					<li>
						Facilitate network operations and security, defend against legal
						claims and enforce our legal rights.
					</li>
					<li>
						Provide information (including location) to an appropriate
						governmental entity in emergency circumstances such as immediate
						danger of death or serious physical injury.
					</li>
					<li>
						Alert the National Center for Missing and Exploited Children to
						information concerning child pornography if we become aware through
						the provision of our services.
					</li>
					<li>
						Share the names, addresses, and telephone numbers of non-mobile
						phone customers with phone directory publishers and directory
						assistance services as required by law. We honor your request for
						non-published or non-listed numbers.
					</li>
					<li>
						Provide name and phone number for wireline and wireless Caller ID
						and related services like Call Trace.
					</li>
				</ul>

				<p>
					<b>Non-AT&amp;T companies for metrics, insights and research.</b> We
					may share aggregated (grouped) data that does not identify you
					personally for these purposes. We require that companies and entities
					agree not to attempt to identify individuals – or allow others to do
					so. We share in this manner for:
					<br />
				</p>
				<ul>
					<li>
						<b>Metrics:</b> Sometimes you enjoy a service from us that directly
						involves another business. For instance, we might provide the Wi-Fi
						service at a place you visit. As part of our service, we may provide
						aggregate metrics reports to that business about how the Wi-Fi is
						being used, such as aggregated location and web-browsing data. It
						can only be used for group insights.
						<br />
					</li>
					<li>
						<b>Insights:</b> We may share aggregated data about our network,
						operations or services.
						<br />
					</li>
					<li>
						<b>Research:</b>&nbsp;We require researchers to handle the data
						securely and not use it for other purposes or further share it.
					</li>
				</ul>
				<p>
					<b>Non-AT&amp;T companies for location services.</b> With your
					consent, we may share your location information for traffic and
					mapping apps and other location services to which you subscribe. We
					share only with your consent, unless required by law. Keep in mind:
				</p>
				<ul>
					<li>
						You may give your consent to us, or you may give it directly to
						another company – like a medical alerting device company.
					</li>
					<li>
						If you give it directly to another company, that company governs the
						use or disclosure of location.
					</li>
					<li>
						In some cases, such as parental controls, consent may come from the
						AT&amp;T account holder and not the individual user.
					</li>
				</ul>

				<h3>Your privacy choices and controls</h3>

				<p>
					You can manage how we use and share your information for certain
					activities including advertising and marketing. Here are key examples:
				</p>
				<p>
					<b>Sharing or selling my personal information.</b> We may share
					limited information to create, deliver, and measure advertisements for
					things you might like. This includes targeted advertising, which may
					be based on personal information obtained from your interactions with
					other businesses. We also share information in ways that may be
					considered a sale of information under some state laws, such as
					exchanging subscriber lists for marketing or sharing identifiers and
					other information with non-AT&amp;T advertising companies to target
					and deliver ads on behalf of advertisers, including AT&amp;T. We do
					not sell your Sensitive Personal Information.
				</p>
				<p>You can ask us to stop at any time, just:</p>
				<ul>
					<li>
						Visit
						<a
							href="https://www.att.com/acctmgmt/passthrough/PRIVACYCHOICES?origination_point=PrivacyCenter"
							target="_blank"
							rel="noopener"
						>
							att.com/PrivacyChoices
						</a>
						or our
						<a
							href="https://about.att.com/privacy/choices-and-controls.html"
							target="_blank"
							rel="noopener"
						>
							Choices and Controls
						</a>
						&nbsp;page to control if we can share or sell your personal
						information.&nbsp;
					</li>
					<li>
						Contact us at (866) 385-3193 if you are a California resident.
					</li>
				</ul>
				<p>
					We recognize and honor the preference signal associated with a
					<a
						href="http://www.globalprivacycontrol.org/"
						target="_blank"
						rel="noopener"
					>
						Global Privacy Control
					</a>
					.
				</p>
				<p>
					<b>Access, delete and correct your personal information. </b>You can
					ask to see what personal information we have about you. You can also
					ask us to delete or correct it. And if we deny your request, you have
					the option to appeal our decision.
				</p>
				<ul>
					<li>
						<b>Access and Portability. </b>If you want to see the personal
						information we’ve collected, you can ask us for it. We will describe
						the categories of information we collect, the specific pieces we’ve
						collected, the sources of the information, the purposes for
						collecting, sharing or selling it and the categories of non-AT&amp;T
						companies with which we shared or sold it. You can also ask to
						“port” your data, which means you get a copy that you can take with
						you.
					</li>
					<li>
						<b>Delete. </b>You can ask us to delete your personal information.
						In keeping with various state laws, please know that we will still
						keep data needed for things like running the business, security and
						fraud protection, compliance with legal obligations, and marketing
						our products and services to our own customers.
						<br />
					</li>
					<li>
						<b>Correct. </b>You can ask us to correct inaccurate personal
						information we have about you. We’ll ask you to provide
						documentation to support the correction and let you know the result.
					</li>
				</ul>
				<p>
					To access, delete, or correct your information, visit our
					<a
						href="https://about.att.com/privacy/choices-and-controls.html"
						target="_blank"
						rel="noopener"
					>
						Choices and Controls
					</a>
					&nbsp;page. California residents can also contact us at (866)
					385-3193. Helpful details about the process can be found at our&nbsp;
					<a
						href="https://www.att.com/mydatarequest/"
						target="_blank"
						title="AT&amp;T Data Request Center"
						rel="noopener"
					>
						Data Request Center
					</a>
					,&nbsp;including your option
					<a
						href="https://www.att.com/mydatarequest/new-request/"
						target="_blank"
						rel="noopener"
					>
						to appeal
					</a>
					. We don’t mind if you make access, deletion, or correction requests,
					or ask us not to sell or share your information. These are rights
					under certain state laws, and we have extended their availability
					across the U.S., regardless of where you live.
				</p>
				<p>
					Depending on your state of residence, you may have additional privacy
					choices. Just visit our
					<a
						href="https://about.att.com/privacy/state-law-approach.html#colorado"
						target="_blank"
						rel="noopener"
					>
						State Law{" "}
					</a>
					<a
						href="https://about.att.com/privacy/state-law-approach.html#colorado"
						target="_blank"
						rel="noopener"
					>
						Approach
					</a>
					page and scroll to your state to learn more.
				</p>
				<p>
					As required by California law, you can review information specifically
					about California requests from the previous calendar year on our
					<a
						href="https://about.att.com/privacy/StateLawApproach/california/ca-metrics.html"
						target="_blank"
						rel="noopener"
					>
						California metrics
					</a>
					&nbsp;page. We also follow state requirements within California
					regarding
					<a
						title="California business customers information"
						href="https://about.att.com/privacy/StateLawApproach/california/ca-biz-customers.html"
						target="_blank"
						rel="noopener"
					>
						businesses and those that provide work
					</a>
					&nbsp;for us.
				</p>

				<h2>Personalized and Personalized Plus</h2>
				<p>
					AT&amp;T has two programs that use your personal information to help
					customize your experience. For instance, you might be shown an online
					advertisement that is more relevant to your interests, rather than a
					general ad.
				</p>
				<p>
					You can choose to participate or not – and it’s never a problem if you
					change your mind. You are automatically enrolled in the Personalized
					program, but you can always opt out. You must opt in to join
					Personalized Plus. Choices for both programs can be made at
					<a
						title="Privacy Choices"
						href="https://att.com/PrivacyChoices"
						target="_blank"
						rel="noopener"
					>
						att.com/PrivacyChoices
					</a>
					.
				</p>
				<p>Here is a comparison of the programs:</p>

				<p>
					Data Use or Sharing Description
					<br />
				</p>

				<table>
					<thead>
						<tr>
							<th>
								<p>
									Data Use or Sharing Description
									<br />
								</p>
							</th>

							<th>
								<p>
									<b>Personalized</b>
								</p>
							</th>

							<th>
								<p>
									<b>Personalized Plus</b>
								</p>
							</th>
						</tr>
					</thead>

					<tbody>
						<tr>
							<td>
								<p>
									Uses data about your use of our products and services,
									including data from apps.
									<br />
								</p>
							</td>

							<td>
								<p>✔</p>
							</td>

							<td>
								<p>✔</p>
							</td>
						</tr>

						<tr>
							<td>
								<p>
									Uses demographic data like age range and ethnicity* that we
									purchase from third parties.
								</p>
							</td>

							<td>
								<p>✔</p>
							</td>

							<td>
								<p>✔</p>
							</td>
						</tr>

						<tr>
							<td>
								<p>Uses data from our advertising partners.</p>
							</td>

							<td>
								<p>✔</p>
							</td>

							<td>
								<p>✔</p>
							</td>
						</tr>

						<tr>
							<td>
								<p>
									Uses automated decision-making, such as artificial
									intelligence.
								</p>
							</td>

							<td>
								<p>✔</p>
							</td>

							<td>
								<p>✔</p>
							</td>
						</tr>

						<tr>
							<td>
								<p>
									Does <b>not </b>use information about your medical conditions
									or financial account information.
								</p>
							</td>

							<td>
								<p>✔</p>
							</td>

							<td>
								<p>✔</p>
							</td>
						</tr>

						<tr>
							<td>
								<p>
									Does <b>not </b>access or use the contents of your texts,
									emails or calls.
								</p>
							</td>

							<td>
								<p>✔</p>
							</td>

							<td>
								<p>✔</p>
							</td>
						</tr>

						<tr>
							<td>
								<p>
									May use precise location and Customer Proprietary Network
									Information for marketing and advertising.
								</p>
							</td>

							<td />

							<td>
								<p>✔</p>
							</td>
						</tr>

						<tr>
							<td>
								<p>
									May use web browsing we collect as your internet provider for
									marketing and advertising and infer websites you visit over a
									secured connection.
								</p>
							</td>

							<td />

							<td>
								<p>✔</p>
							</td>
						</tr>
					</tbody>
				</table>

				<p>
					*If you live in certain states, we won’t collect, use, store or share
					your sensitive personal information for marketing and advertising
					unless you join Personalized Plus. This includes information like
					ethnicity and racial origin. The states are Colorado, Connecticut,
					Delaware, Indiana, Iowa, Kentucky, Maryland, Minnesota, Montana,
					Nebraska, New Hampshire, New Jersey, Oregon, Tennessee, Texas, Utah
					and Virginia.
				</p>
				<p>
					If you join the Personalized Plus program, it is an extension of the
					Personalized program, so you will be enrolled in both. But you can
					always stop the sharing or selling of your personal information at
					att.com/privacychoices or our
					<a
						href="https://about.att.com/privacy/choices-and-controls.html"
						target="_blank"
						rel="noopener"
					>
						Choices and Controls
					</a>
					page.
				</p>

				<h2>More choices and controls</h2>
				<p>
					<b>Customer Proprietary Network Information (CPNI).&nbsp;</b>CPNI is
					information related to the telecommunications services you purchase
					from us, such as which subscription plan you have and details about
					who you called. Your phone number, name and address are not CPNI. It
					is your right and our duty under federal law to protect the
					confidentiality of your CPNI.
				</p>
				<p>
					You can choose whether we use your CPNI internally for marketing –
					such as helping to offer you new services and promotions.&nbsp;
				</p>
				<p>
					You can opt out at
					<a
						title="AT&amp;T CPNI Opt Out"
						href="https://att.com/cpni/optout"
						target="_blank"
						rel="noopener"
					>
						att.com/cpni/optout
					</a>
					. You can also call us any time at (800) 315-8303 and follow the
					prompts. Or you can talk to a service representative at (800) 288-2020
					(consumer) or (800) 321-2000 (business).
				</p>
				<p>
					We don’t share CPNI outside of our AT&amp;T affiliates, agents, and
					suppliers without your consent, except for court orders, fraud
					detection, providing service, network operations, and security;
					aggregate (grouped) information that doesn’t identify you personally
					and as otherwise authorized by law.
				</p>
				<p>
					I​f you choose to restrict our use of CPNI, it won’t affect your
					services. We keep your choice until you change your mind, which you
					can do at any time. Keep in mind, if you restrict use of your CPNI,
					you may still get marketing from us.
				</p>
				<p>
					<b>Identity verification.</b>&nbsp;Non-AT&amp;T companies like your
					bank may receive limited information from us to help protect your
					accounts from fraud, verify your identity and make sure it’s really
					you authorizing a transaction. We do not allow these non-AT&amp;T
					companies to use your information for any other purpose. You are
					generally enrolled through the non-AT&amp;T company, but you can stop
					at any time through us. Text “STOP” to 8010 to turn off Identity
					Verification, or text “RESUME” to restart. Or manage your choices at
					<a
						href="https://www.att.com/acctmgmt/passthrough/PRIVACYCHOICES?origination_point=PrivacyCenter"
						target="_blank"
						rel="noopener"
					>
						att.com/PrivacyChoices
					</a>
					.
				</p>
				<p>
					<b>Contact preferences. </b>We like to tell you about offers and
					programs that may interest you. You can manage how we do that. Keep in
					mind that we still may need to contact you with service and
					non-marketing messages. Please visit
					<a
						href="https://about.att.com/privacy/privacy-notice/contact-preferences.html"
						target="_blank"
						rel="noopener"
					>
						Contact Preferences
					</a>
					for more information and links.
				</p>

				<h2>Industry choices and controls</h2>
				<p>
					<b>Online behavioral advertising.</b> You have industry-wide choices
					about online, interest-based advertising.
				</p>
				<p>
					Companies including AT&amp;T may use cookies, mobile advertising
					identifiers, and other technologies to collect information about your
					use of websites including ours. This information can be used to
					analyze and track online activity or deliver ads and content tailored
					to your interests.
				</p>
				<p>
					You can opt out of online behavioral advertising from companies that
					participate in the
					<a href="http://www.aboutads.info/" target="_blank" rel="noopener">
						Digital Advertising Alliance
					</a>
					. Go to their
					<a
						href="http://www.aboutads.info/choices/#completed"
						target="_blank"
						rel="noopener"
					>
						Consumer Choice Page
					</a>
					. You can also select this icon
					<img
						src="https://about.att.com/ecms/dam/csr/privacy-redesign/ad_info_icon.gif"
						alt="Consumer Choice Page"
						className="mx-1 inline"
					/>
					when you see it on an online ad.
				</p>
				<ul>
					<li>
						You can limit collection of data on websites by
						<a
							href="https://about.att.com/privacy/privacy-notice/cookies.html"
							target="_blank"
							rel="noopener"
						>
							managing cookies and similar technologies
						</a>
						on your computer. Remember that if you change computers, devices, or
						web browsers, or if you delete cookies, you will need to manage them
						again.
						<br />
					</li>
				</ul>
				<p>
					At AT&amp;T, please note that when we collect web browsing information
					as an internet service provider, it works independently of your web
					browser’s cookie and private browsing settings that interact with
					online behavioral advertising. You can manage AT&amp;T’s use of web
					browsing information – such as our Personalized Plus program – at
					<a
						title="AT&amp;T Privacy Choices"
						href="https://att.com/PrivacyChoices"
						target="_blank"
						rel="noopener"
					>
						att.com/PrivacyChoices
					</a>
					.
				</p>
				<p>
					We don’t currently respond to Do Not Track. Please go to
					<a
						title="All About Do Not Track"
						href="http://www.allaboutdnt.com/"
						target="_blank"
						rel="noopener"
					>
						All About Do Not Track
					</a>
					for more information.
				</p>
				<p>
					Unless you join our Personalized Plus ad program, we don’t knowingly
					allow non-AT&amp;T companies to collect your personally identifiable
					activity on our websites for their own use and tracking.
				</p>

				<h3>Data retention and security</h3>

				<p>
					We keep your information as long as we need it for business, tax, or
					legal purposes. We set our retention periods based on things like what
					type of personal information it is, how long it’s needed to operate
					the business or provide our products and services, and whether it’s
					subject to contractual or legal obligations. These obligations might
					be ongoing litigation, mandatory data retention laws or government
					orders to preserve data for an investigation. After that, we destroy
					it by making it unreadable or indecipherable.
				</p>
				<p>
					We work hard to safeguard your information using technology controls
					and organizational controls. We protect our computer storage and
					network equipment. We require employees to authenticate themselves to
					access sensitive data. We limit access to personal information to the
					people who need access for their jobs. And we require callers and
					online users to authenticate themselves before we provide account
					information.
				</p>
				<p>
					No security measures are perfect. We can’t guarantee that your
					information will never be disclosed in a manner inconsistent with this
					notice. If a breach occurs, we’ll notify you as required by law.
				</p>

				<h3>Information that we collect and share – in chart format</h3>

				<p>
					<a
						href="https://about.att.com/privacy/privacy-notice/state-disclosures.html#we-collect"
						target="_blank"
						rel="noopener"
					>
						This chart
					</a>
					shows the personal information that we collect, along with the purpose
					for its collection.
				</p>
				<p>
					<a
						href="https://about.att.com/privacy/privacy-notice/state-disclosures.html#about-consumers"
						target="_blank"
						rel="noopener"
					>
						This chart
					</a>
					shows the personal information we shared or sold over the past year
					about at least some consumers. It also shows the purpose for which we
					shared or sold it. Some states define “sale” very broadly.
				</p>
				<p>
					<a
						href="https://about.att.com/privacy/privacy-notice/state-disclosures.html#sensitive-personal-info"
						target="_blank"
						rel="noopener"
					>
						This chart
					</a>
					&nbsp;shows the sensitive personal information we’ve collected about
					consumers over the past year, including the purpose for its collection
					and sharing. AT&amp;T does not sell your Sensitive Personal
					Information.
				</p>

				<h3>Changes in ownership or to the notice</h3>

				<p>
					Information about you may be shared or transferred if AT&amp;T is part
					of a merger, acquisition, sale of company assets or lines of business,
					or transition of service to another provider. Information could also
					be shared in the unlikely event that our business were to become
					insolvent or bankrupt or were put into receivership.
				</p>
				<p>
					We update this Privacy Notice as necessary to reflect business changes
					and satisfy legal requirements. We post a prominent notice on our
					websites of any material changes. We give you reasonable notice before
					any material changes take effect.
				</p>

				<h3>Information specific to business customers</h3>

				<p>
					We only use our business customers’ user information for marketing or
					advertising when we market business products and services, including
					apps and devices. However, we may use our relationship with you to
					qualify you for certain deals on consumer products and services. You
					can call the toll-free number on your bill to see whether your current
					products and services are billed as business or consumer.
				</p>

				<h3>Information specific to children</h3>

				<p>
					We don’t knowingly collect personal information from anyone under 18
					without parental notice, and we get parental consent where
					appropriate. We also won’t contact a child under 18 for marketing
					purposes without parental consent. However, if we are not aware that a
					child is using a service or device purchased by an adult, we may
					collect the information and treat it as the adult’s. (See
					<a
						href="https://www.att.com/acctmgmt/passthrough/PRIVACYCHOICES?origination_point=PrivacyCenter"
						target="_blank"
						rel="noopener"
					>
						your privacy choices
					</a>
					.)
				</p>
				<p>
					We do not sell personal information of anyone we know who is under 18,
					unless we receive affirmative permission to do so. If a child is under
					18 and at least 13, the child may provide the permission.
				</p>
				<p>
					We provide additional disclosures regarding certain products and
					services where we have reason to believe that we are collecting and
					using information from children under 18. For more information, please
					review our
					<a
						href="https://about.att.com/privacy/additional-privacy-notices/childrens-privacy-notice.html"
						target="_blank"
						rel="noopener"
					>
						AT&amp;T Privacy Notice for Children’s Products and Services
					</a>
					.
				</p>

				<h3>How to contact us about this notice</h3>

				<p>
					You can
					<a
						href="https://www.att.com/mydatarequest/att/submit-inquiry-nocaseid/"
						target="_blank"
						rel="noopener"
					>
						contact us with questions
					</a>
					about this notice. You can also write us at AT&amp;T Privacy Notice,
					Chief Privacy Office, 208 S. Akard, Room 2901, Dallas, TX, 75202.
				</p>
				<p>
					If you have questions not related to privacy, click on the “Contact
					Us” link on the bottom of any att.com page.
				</p>
				<p>
					You can access your online account from the upper right-hand corner of
					our home page at att.com.
				</p>
				<p>
					If you’re not satisfied with our resolution of any dispute, including
					privacy and personal information concerns, you can learn about our
					dispute resolution procedures on our
					<a
						href="https://www.att.com/help/notice-of-dispute/"
						target="_blank"
						rel="noopener"
					>
						dispute resolution page
					</a>
					.
				</p>
				<p>
					You also have the option to file a complaint with the FTC Bureau of
					Consumer Protection using an&nbsp;
					<a
						title="Report fraud with the FTC"
						href="https://reportfraud.ftc.gov/#/"
						target="_blank"
						rel="noopener"
					>
						online form
					</a>
					or calling toll-free to 877.FTC.HELP ((877) 382.4357; TTY: (866)
					653.4261). Other rights and remedies also may be available to you
					under federal or other laws.
					<br />
				</p>
			</div>
		</div>
	);

	return createPortal(modalContent, document.body);
}
